-- Step 2 SRM domain schema (MySQL 8+).
-- This script is additive and is NOT wired into Spring's automatic SQL initialization.
-- Apply explicitly to a local development database after reviewing it.

CREATE TABLE IF NOT EXISTS `srm_supplier` (
    `supplier_id`       VARCHAR(64) NOT NULL COMMENT '内部供应商ID',
    `supplier_code`     VARCHAR(64) NOT NULL COMMENT '可读供应商编码',
    `supplier_name`     VARCHAR(256) NOT NULL COMMENT '供应商名称（演示数据均为合成）',
    `supply_category`   VARCHAR(128) NOT NULL COMMENT '主要供货品类',
    `status`            VARCHAR(32) NOT NULL COMMENT 'POTENTIAL/QUALIFIED/SUSPENDED/DISQUALIFIED',
    `risk_level`        VARCHAR(16) NOT NULL DEFAULT 'LOW' COMMENT 'LOW/MEDIUM/HIGH/CRITICAL',
    `quality_score`     DECIMAL(5,2) DEFAULT NULL COMMENT '质量评分，0-100',
    `delivery_score`    DECIMAL(5,2) DEFAULT NULL COMMENT '交付评分，0-100',
    `payment_terms_days` INT DEFAULT NULL COMMENT '账期（天）',
    `country_region`    VARCHAR(128) DEFAULT NULL COMMENT '国家或区域',
    `contact_name`      VARCHAR(128) DEFAULT NULL COMMENT '业务联系人（演示）',
    `contact_email`     VARCHAR(256) DEFAULT NULL COMMENT '业务邮箱（演示）',
    `risk_note`         VARCHAR(512) DEFAULT NULL COMMENT '风险说明',
    `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`supplier_id`),
    UNIQUE KEY `uk_srm_supplier_code` (`supplier_code`),
    KEY `idx_srm_supplier_status_risk` (`status`, `risk_level`),
    CONSTRAINT `ck_srm_supplier_quality_score` CHECK (`quality_score` IS NULL OR (`quality_score` >= 0 AND `quality_score` <= 100)),
    CONSTRAINT `ck_srm_supplier_delivery_score` CHECK (`delivery_score` IS NULL OR (`delivery_score` >= 0 AND `delivery_score` <= 100)),
    CONSTRAINT `ck_srm_supplier_payment_terms` CHECK (`payment_terms_days` IS NULL OR `payment_terms_days` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM供应商主数据';

CREATE TABLE IF NOT EXISTS `srm_rfq_project` (
    `rfq_id`                 VARCHAR(64) NOT NULL COMMENT '内部RFQ ID',
    `rfq_no`                 VARCHAR(64) NOT NULL COMMENT 'RFQ编号',
    `project_name`           VARCHAR(256) NOT NULL COMMENT '寻源项目名称',
    `material_code`          VARCHAR(64) NOT NULL COMMENT '物料编码',
    `material_name`          VARCHAR(256) NOT NULL COMMENT '物料名称',
    `required_quantity`      DECIMAL(18,3) NOT NULL COMMENT '需求数量',
    `unit`                   VARCHAR(16) NOT NULL COMMENT '计量单位',
    `required_delivery_date` DATE DEFAULT NULL COMMENT '期望到货日期',
    `quotation_deadline`     DATETIME DEFAULT NULL COMMENT '报价截止时间',
    `budget_amount`          DECIMAL(18,2) DEFAULT NULL COMMENT '预算金额',
    `currency`               VARCHAR(8) NOT NULL DEFAULT 'CNY',
    `status`                 VARCHAR(32) NOT NULL COMMENT 'DRAFT/PUBLISHED/QUOTING/QUOTE_CLOSED/EVALUATING/AWARDED/CANCELLED',
    `owner_id`               VARCHAR(64) NOT NULL COMMENT '采购负责人ID',
    `award_supplier_id`      VARCHAR(64) DEFAULT NULL COMMENT '中选供应商；逻辑引用，定点时校验',
    `award_quote_id`         VARCHAR(64) DEFAULT NULL COMMENT '中选报价；逻辑引用，定点时校验',
    `created_at`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`rfq_id`),
    UNIQUE KEY `uk_srm_rfq_no` (`rfq_no`),
    KEY `idx_srm_rfq_status_deadline` (`status`, `quotation_deadline`),
    KEY `idx_srm_rfq_material` (`material_code`),
    KEY `idx_srm_rfq_award_supplier` (`award_supplier_id`),
    CONSTRAINT `ck_srm_rfq_required_quantity` CHECK (`required_quantity` > 0),
    CONSTRAINT `ck_srm_rfq_budget_amount` CHECK (`budget_amount` IS NULL OR `budget_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM寻源项目与RFQ';

CREATE TABLE IF NOT EXISTS `srm_supplier_quote` (
    `quote_id`          VARCHAR(64) NOT NULL COMMENT '内部报价ID',
    `quote_no`          VARCHAR(64) NOT NULL COMMENT '报价单编号',
    `rfq_id`            VARCHAR(64) NOT NULL COMMENT '关联RFQ',
    `supplier_id`       VARCHAR(64) NOT NULL COMMENT '报价供应商',
    `quote_version`     INT NOT NULL DEFAULT 1 COMMENT '同一供应商对同一RFQ的版本号',
    `status`            VARCHAR(32) NOT NULL COMMENT 'DRAFT/SUBMITTED/WITHDRAWN/EXPIRED/REJECTED/ACCEPTED',
    `unit_price`        DECIMAL(18,4) NOT NULL COMMENT '未税单价',
    `quoted_quantity`   DECIMAL(18,3) NOT NULL COMMENT '报价数量',
    `tax_rate`          DECIMAL(5,4) NOT NULL DEFAULT 0 COMMENT '税率，例如0.1300',
    `total_amount`      DECIMAL(18,2) NOT NULL COMMENT '含税报价总额',
    `currency`          VARCHAR(8) NOT NULL DEFAULT 'CNY',
    `lead_time_days`    INT DEFAULT NULL COMMENT '交付周期（天）',
    `valid_until`       DATE DEFAULT NULL COMMENT '报价有效截止日',
    `submitted_at`      DATETIME DEFAULT NULL COMMENT '提交时间',
    `risk_note`         VARCHAR(512) DEFAULT NULL COMMENT '报价或供应风险备注',
    `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`quote_id`),
    UNIQUE KEY `uk_srm_quote_no` (`quote_no`),
    UNIQUE KEY `uk_srm_quote_rfq_supplier_version` (`rfq_id`, `supplier_id`, `quote_version`),
    KEY `idx_srm_quote_supplier_status` (`supplier_id`, `status`),
    KEY `idx_srm_quote_rfq_status` (`rfq_id`, `status`),
    CONSTRAINT `fk_srm_quote_rfq` FOREIGN KEY (`rfq_id`) REFERENCES `srm_rfq_project` (`rfq_id`),
    CONSTRAINT `fk_srm_quote_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `srm_supplier` (`supplier_id`),
    CONSTRAINT `ck_srm_quote_unit_price` CHECK (`unit_price` >= 0),
    CONSTRAINT `ck_srm_quote_quantity` CHECK (`quoted_quantity` > 0),
    CONSTRAINT `ck_srm_quote_tax_rate` CHECK (`tax_rate` >= 0 AND `tax_rate` <= 1),
    CONSTRAINT `ck_srm_quote_total_amount` CHECK (`total_amount` >= 0),
    CONSTRAINT `ck_srm_quote_lead_time` CHECK (`lead_time_days` IS NULL OR `lead_time_days` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM供应商报价（可版本化）';

CREATE TABLE IF NOT EXISTS `srm_price_library_record` (
    `price_record_id`         VARCHAR(64) NOT NULL COMMENT '价格库记录ID',
    `supplier_id`             VARCHAR(64) NOT NULL COMMENT '供应商',
    `material_code`           VARCHAR(64) NOT NULL COMMENT '物料编码',
    `material_name`           VARCHAR(256) NOT NULL COMMENT '物料名称',
    `unit`                    VARCHAR(16) NOT NULL COMMENT '计量单位',
    `unit_price`              DECIMAL(18,4) NOT NULL COMMENT '未税单价',
    `currency`                VARCHAR(8) NOT NULL DEFAULT 'CNY',
    `minimum_order_quantity`  DECIMAL(18,3) NOT NULL DEFAULT 1 COMMENT '最小起订量',
    `effective_start_date`    DATE NOT NULL COMMENT '生效开始日',
    `effective_end_date`      DATE NOT NULL COMMENT '生效结束日',
    `status`                  VARCHAR(16) NOT NULL COMMENT 'VALID/EXPIRING/EXPIRED/SUSPENDED',
    `source_quote_id`         VARCHAR(64) DEFAULT NULL COMMENT '来源报价，可为空（历史导入）',
    `remark`                  VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `created_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`price_record_id`),
    UNIQUE KEY `uk_srm_price_supplier_material_start` (`supplier_id`, `material_code`, `effective_start_date`),
    KEY `idx_srm_price_material_status_date` (`material_code`, `status`, `effective_end_date`),
    KEY `idx_srm_price_supplier_status` (`supplier_id`, `status`),
    CONSTRAINT `fk_srm_price_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `srm_supplier` (`supplier_id`),
    CONSTRAINT `fk_srm_price_source_quote` FOREIGN KEY (`source_quote_id`) REFERENCES `srm_supplier_quote` (`quote_id`),
    CONSTRAINT `ck_srm_price_unit_price` CHECK (`unit_price` >= 0),
    CONSTRAINT `ck_srm_price_moq` CHECK (`minimum_order_quantity` > 0),
    CONSTRAINT `ck_srm_price_effective_date` CHECK (`effective_end_date` >= `effective_start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM价格库记录';

CREATE TABLE IF NOT EXISTS `srm_purchase_order` (
    `purchase_order_id`       VARCHAR(64) NOT NULL COMMENT '内部采购订单ID',
    `po_no`                   VARCHAR(64) NOT NULL COMMENT '采购订单编号',
    `supplier_id`             VARCHAR(64) NOT NULL COMMENT '下单供应商',
    `source_rfq_id`           VARCHAR(64) DEFAULT NULL COMMENT '来源RFQ',
    `selected_quote_id`       VARCHAR(64) DEFAULT NULL COMMENT '中选报价',
    `status`                  VARCHAR(32) NOT NULL COMMENT 'DRAFT/PENDING_APPROVAL/APPROVED/RELEASED/PARTIALLY_RECEIVED/RECEIVED/CLOSED/CANCELLED',
    `purchaser_id`            VARCHAR(64) NOT NULL COMMENT '采购员ID',
    `order_date`              DATE NOT NULL COMMENT '下单日期',
    `expected_delivery_date`  DATE DEFAULT NULL COMMENT '期望到货日',
    `currency`                VARCHAR(8) NOT NULL DEFAULT 'CNY',
    `total_amount`            DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '含税订单总额',
    `high_risk_review_required` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '高风险人工复核标识',
    `remark`                  VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `created_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`purchase_order_id`),
    UNIQUE KEY `uk_srm_po_no` (`po_no`),
    KEY `idx_srm_po_supplier_status` (`supplier_id`, `status`),
    KEY `idx_srm_po_rfq` (`source_rfq_id`),
    KEY `idx_srm_po_expected_delivery` (`expected_delivery_date`, `status`),
    CONSTRAINT `fk_srm_po_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `srm_supplier` (`supplier_id`),
    CONSTRAINT `fk_srm_po_rfq` FOREIGN KEY (`source_rfq_id`) REFERENCES `srm_rfq_project` (`rfq_id`),
    CONSTRAINT `fk_srm_po_quote` FOREIGN KEY (`selected_quote_id`) REFERENCES `srm_supplier_quote` (`quote_id`),
    CONSTRAINT `ck_srm_po_total_amount` CHECK (`total_amount` >= 0),
    CONSTRAINT `ck_srm_po_high_risk_review` CHECK (`high_risk_review_required` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM采购订单头';

CREATE TABLE IF NOT EXISTS `srm_purchase_order_line` (
    `id`                  BIGINT NOT NULL AUTO_INCREMENT,
    `purchase_order_id`   VARCHAR(64) NOT NULL COMMENT '采购订单头',
    `line_no`             INT NOT NULL COMMENT '行号，从1开始',
    `material_code`       VARCHAR(64) NOT NULL COMMENT '物料编码',
    `material_name`       VARCHAR(256) NOT NULL COMMENT '物料名称',
    `unit`                VARCHAR(16) NOT NULL COMMENT '计量单位',
    `ordered_quantity`    DECIMAL(18,3) NOT NULL COMMENT '订单数量',
    `received_quantity`   DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '累计收货数量',
    `unit_price`          DECIMAL(18,4) NOT NULL COMMENT '未税单价',
    `tax_rate`            DECIMAL(5,4) NOT NULL DEFAULT 0 COMMENT '税率',
    `status`              VARCHAR(32) NOT NULL COMMENT 'OPEN/PARTIALLY_RECEIVED/RECEIVED/CANCELLED',
    `remark`              VARCHAR(512) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_srm_po_line` (`purchase_order_id`, `line_no`),
    KEY `idx_srm_po_line_material_status` (`material_code`, `status`),
    CONSTRAINT `fk_srm_po_line_header` FOREIGN KEY (`purchase_order_id`) REFERENCES `srm_purchase_order` (`purchase_order_id`) ON DELETE CASCADE,
    CONSTRAINT `ck_srm_po_line_no` CHECK (`line_no` > 0),
    CONSTRAINT `ck_srm_po_line_ordered_quantity` CHECK (`ordered_quantity` > 0),
    CONSTRAINT `ck_srm_po_line_received_quantity` CHECK (`received_quantity` >= 0 AND `received_quantity` <= `ordered_quantity`),
    CONSTRAINT `ck_srm_po_line_unit_price` CHECK (`unit_price` >= 0),
    CONSTRAINT `ck_srm_po_line_tax_rate` CHECK (`tax_rate` >= 0 AND `tax_rate` <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SRM采购订单明细';
